/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dip_angrycamera_angrycamera_MyActivity_PlaceholderFragment */

#ifndef _Included_com_dip_angrycamera_angrycamera_MyActivity_PlaceholderFragment
#define _Included_com_dip_angrycamera_angrycamera_MyActivity_PlaceholderFragment
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
